sudo: required
dist: trusty
language: c

before_install:
    # update package list
    - sudo apt-get update -qq
    # installneeded packages for uscan
    - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl
    # download original tarball
    - UVERSION=$(dpkg-parsechangelog | grep ^Version | cut -d' ' -f2 | cut -d'-' -f1); uscan --verbose --download-version ${UVERSION} --force-download
    # remove packages needed for uscan
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get autoremove -qq

install:
    # install packages needed for mk-build-deps
    - sudo apt-get install -qq --no-install-recommends devscripts equivs
    # pull build deps from debian/control
    - sudo mk-build-deps -ir -t "apt-get --yes --no-install-recommends"
    - wget "https://github.com/waja-archive/pyaml/releases/download/debian%2F${PYAML_VERSION}/python-pyaml_${PYAML_VERSION}_all.deb" -O /tmp/python-pyaml_all.deb
    - dpkg -i /tmp/python-pyaml_all.deb
    # remove packages needed for mk-build-deps
    - sudo apt-get purge -qq equivs
    - sudo apt-get autoremove -qq

script:
    # build the debian package
    - dpkg-buildpackage -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc

env:
  global:
    - PYAML_VERSION=15.8.2-2
    # travis encrypt -r waja/sail GITHUBTOKEN=XXXXXX (https://help.github.com/articles/creating-an-access-token-for-command-line-use / http://docs.travis-ci.com/user/encryption-keys/)
    - secure: "WDbWkU9tqfplokfFJvLaIYRKa40LNuLXYK6kUggs/GGSvUHBmvs/PQXzJwJPhWU2rfhvykIspUVd7O2LiifrThMLjYK1aH3AzS+WZzPUclLbFg1hx4+trO/SOe3Bl/UlSFo317IB5r5y6f+BrpWT+0UYSdiYLN3J5hJL2o0H/zOHWzDy2TMnUBwzFz2k2ifAj6WcxlMNVGRhzt22OAdn+OqlTSqhrvenyEhNHEID8QZqrqfVULOxWi2won4/tBIxu+N7re2vuHt7l+Wb+t/yVmfWWcV+Ll3HQpOH2QRW2RwdKxnbxx/x+cD/zywBsjf2AEvSys7SqDDXBcCiJQXCXQHsakMbMYkOMp/el5erCdv/4nQ3gnAOqyUA6DsIZD77UeeJMXrFZ2F6sRonCmqYniqbH+Wh6Nn2MAW3nfXZN78axxG82vVqI4BKykP9MIC5qvBX5QGj2GuIFC7iqsPHpvxn+8bpOTd06pbAI/UXBezNpf7TXAfNO6uU7+tsMKX0uhAD+aPKC7kbm58vZCVZWJ5NrLZRnE0vPJuFfbhJ3mjaEe1EFQxUKLHGwYzERrIWHjTR8yeid4duy80Vw99t25xH3f3aoA7hPjks/yEFU+Y2Ck74z6Y7oam0PFPiW4k+6Lu2taX7/EyiSPPjAskjAlNv0XUff97X+SLouTDxg8I="

after_success:
    - mkdir -p debian/build/release/
    - for FILE in $(dcmd ../*.changes); do cp ../$(basename $FILE) debian/build/release/; done
    - debian/bin/github-release.sh "$TRAVIS_REPO_SLUG" "debian/`head -1 debian/changelog | awk -F'[()]' '{print $2}' | awk -F'+' '{print $1}'`" debian/build/release/*

#notifications:
#  email: false
